
export const DEPARTMENT_OPTIONS = [
  { label: "LDR", value: "LDR" },
  { label: "IM", value: "IM" },
  { label: "ENT", value: "ENT" },
  { label: "OPTHA", value: "OPTHA" },
  { label: "DERMA", value: "DERMA" },
  { label: "ENDOSCOPY", value: "ENDOSCOPY" },
  { label: "NURSERY", value: "NURSERY" },
  { label: "OB-GYN", value: "OB-GYN" },
  { label: "X-RAY", value: "X-RAY" },
  { label: "OR", value: "OR" },
  { label: "ER", value: "ER" },
  { label: "PT", value: "PT" },
  { label: "IVF", value: "IVF" },
  { label: "CSSD", value: "CSSD" },
  { label: "5 A", value: "5 A" },
  { label: "5 B", value: "5 B" },
  { label: "6 A", value: "6 A" },
  { label: "6 B", value: "6 B" },
  { label: "4A", value: "4A" },
  { label: "4 B", value: "4 B" },
  { label: "DENTAL", value: "DENTAL" },
  { label: "PEDIA", value: "PEDIA" },
  { label: "PLASTIC", value: "PLASTIC" },
  { label: "LAUNDRY", value: "LAUNDRY" },
  { label: "LABORATORY", value: "LABORATORY" },
  { label: "GENERAL SURGERY", value: "GENERAL SURGERY" }
];
