// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxrsuzsypswseotxzeei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cnN1enN5cHN3c2VvdHh6ZWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjExNDIsImV4cCI6MjA2MTEzNzE0Mn0.5Qer6PL8BeIyWHumcsM4Qn-1_rnKo0CBZrG_FPZJpTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);